const NEXT_PUBLIC_GA_TRACKING_ID = process.env.NEXT_PUBLIC_GA_TRACKING_ID
const NOTION_LANGUAGE_API_SECRET = process.env.NOTION_LANGUAGE_API_SECRET
const DATABASE_LANGUAGE_ID = process.env.DATABASE_LANGUAGE_ID

export { DATABASE_LANGUAGE_ID, NEXT_PUBLIC_GA_TRACKING_ID, NOTION_LANGUAGE_API_SECRET }
