const NEXT_PUBLIC_GA_TRACKING_ID = process.env.NEXT_PUBLIC_GA_TRACKING_ID
const NEXT_PUBLIC_NOTION_LANGUAGE_API_SECRET = process.env.NEXT_PUBLIC_NOTION_LANGUAGE_API_SECRET
const NEXT_PUBLIC_DATABASE_LANGUAGE_ID = process.env.NEXT_PUBLIC_DATABASE_LANGUAGE_ID
const NEXT_PUBLIC_API_URL = process.env.NEXT_PUBLIC_API_URL

export {
  NEXT_PUBLIC_API_URL,
  NEXT_PUBLIC_DATABASE_LANGUAGE_ID,
  NEXT_PUBLIC_GA_TRACKING_ID,
  NEXT_PUBLIC_NOTION_LANGUAGE_API_SECRET,
}
